// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMCXXT__tMQf2kuERdLf3l59l4M57Hx8U',
    appId: '1:1069937425099:web:88b594905d2338592db94e',
    messagingSenderId: '1069937425099',
    projectId: 'testwhiteboard-ecf26',
    authDomain: 'testwhiteboard-ecf26.firebaseapp.com',
    storageBucket: 'testwhiteboard-ecf26.firebasestorage.app',
    measurementId: 'G-S7YEZY3RLZ',
    databaseURL: "https://testwhiteboard-ecf26-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINhxauRY8NWGUbbVJZwp-dNIxrriYWSQ',
    appId: '1:1069937425099:android:1b7a17a9fc8210fa2db94e',
    messagingSenderId: '1069937425099',
    projectId: 'testwhiteboard-ecf26',
    storageBucket: 'testwhiteboard-ecf26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-CnoaKM0SsrPkqjAe0yQZ_UV7OQ_Nk8',
    appId: '1:1069937425099:ios:ff39b138959c47122db94e',
    messagingSenderId: '1069937425099',
    projectId: 'testwhiteboard-ecf26',
    storageBucket: 'testwhiteboard-ecf26.firebasestorage.app',
    iosBundleId: 'com.example.testwhiteboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-CnoaKM0SsrPkqjAe0yQZ_UV7OQ_Nk8',
    appId: '1:1069937425099:ios:ff39b138959c47122db94e',
    messagingSenderId: '1069937425099',
    projectId: 'testwhiteboard-ecf26',
    storageBucket: 'testwhiteboard-ecf26.firebasestorage.app',
    iosBundleId: 'com.example.testwhiteboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMCXXT__tMQf2kuERdLf3l59l4M57Hx8U',
    appId: '1:1069937425099:web:16743946fec973862db94e',
    messagingSenderId: '1069937425099',
    projectId: 'testwhiteboard-ecf26',
    authDomain: 'testwhiteboard-ecf26.firebaseapp.com',
    storageBucket: 'testwhiteboard-ecf26.firebasestorage.app',
    measurementId: 'G-5G6ER0R3DV',
  );
}
